Fix tabs

diff --git a/bin/plugin_info b/bin/plugin_info
--- a/bin/plugin_info
+++ b/bin/plugin_info
@@ -1,8 +1,8 @@
 if [ $# -lt 1 ] || [ $# -gt 2 ]
 then
-  echo "Invalid number of arguments. Expected 1-2 got ${#}."
-  echo "Usage: 'get_plugin_info [file] [property]'"
-  exit 1
+	echo "Invalid number of arguments. Expected 1-2 got ${#}."
+	echo "Usage: 'get_plugin_info [file] [property]'"
+  	exit 1
 fi
 
 # Default parses plugin names
@@ -10,10 +10,10 @@ property=2
 
 if [[ $2 == inputs ]]
 then
-  property=4
+  	property=4
 elif [[ $2 == outputs ]]
 then
-  property=6
+  	property=6
 fi
 
 # From each line in the input, get the $property field using space as the delimiter.
