Update tests

diff --git a/bin/run_tests b/bin/run_tests
--- a/bin/run_tests
+++ b/bin/run_tests
@@ -4,13 +4,15 @@ failed=0
 
 clean_output
 
+re='^[0-9]+'
+
 for test in `ls -d */ | egrep '^[0-9]{2}_.*'`
 do
   echo "Testing: $test"
   total=$(( $total + 1 ))
   # Result will tell us how many lines are different between the expected dot file and the generated one.
-  result=`(cd $test ; viz_pipe config* ; (diff -y --suppress-common-lines expected.dot config*.dot | wc -l))`
-  if [[ $result -ne 0 ]]
+  result=`(cd $test ; viz_pipe config* ; cmp --silent expected.dot config*.dot) || echo 'fail'`
+  if [[ "$result" =~ "fail" ]]
   then
     failed=$(( $failed + 1 ))
     echo "  Fail"
diff --git a/bin/viz_pipe b/bin/viz_pipe
--- a/bin/viz_pipe
+++ b/bin/viz_pipe
@@ -1,8 +1,14 @@
+if [[ ! -e $1 ]]
+then
+	printf "File $1 not found.\n"
+  exit 1
+fi
+
 dot_file=$1.dot
 
 parse_pipe.awk $1 > $dot_file
 
 if [[ $2 == png ]]
 then
-  dot -Tpng -O $dotFile
+  dot -Tpng -O $dot_file
 fi
